### ISSUE TITLE
Include resource pack in mod

### ISSUE THREAD

**Issue by AwesomeKalin** [TheMysterys/MCCI-Utils#3]
As you know, MCCI uses a resource pack. I would like this to enable the resource pack at the launch of the game as with some low-end system, like mine, Minecraft just crashes when trying to load in the resource pack. I do realise that due to copyright, you may not be able to, but at least do it after a successful first download of the pack when you first connect to the server with the mod. Thanks!

**Comment by AwesomeKalin** [comment]
An alternative version would be to enable the resource pack BEFORE connecting to the server, also solving the problem

**Comment by TheMysterys** [comment]
Sadly I will not be including the resource pack in the mod due to a few reasons (though I'll list a few here for you), one being copyright and another being the fact that the pack is locked in a way to prevent the average player knowing how to access it and if I was to include it, I wouldn't be able to provide the same protection to the pack. 

Because of those reasons and some others I won't be including the pack in the mod sorry.
